<?php

/**
 * Unit tests for FieldKeyExtractor implementations.
 *
 * Covers PRD §10 requirement 2 (natural-key stability) and the Risk 1 item
 * ("nk:" prefix collision) raised by the Round-1 team.
 *
 * Tests are fully isolated — no database, no OpenEMR globals required.
 *
 * Cross-teammate Risk 1 (from the Round-1 report):
 *   co_pilot_fhir_links.source_block_id stores both real Docling block ids
 *   AND natural-key strings prefixed with "nk:".  A real Docling block_id
 *   that happens to start with "nk:" would be indistinguishable from a
 *   natural-key carrier in the lookup query.
 *
 *   Our test pins that Docling uses "block_N" format (as generated by
 *   _run_docling_layout in __init__.py, lines 222-233).  A block_id that
 *   starts with "nk:" is therefore outside the Docling output contract.
 *   The test documents this constraint; if Docling ever emits "nk:"-prefixed
 *   ids the disambiguation logic in RoundtripService must be updated.
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    AgentForge Team
 * @copyright Copyright (c) 2026 AgentForge
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Tests\Unit\CoPilotModule;

use OpenEMR\Modules\ClinicalCopilot\Service\FieldKeyExtractor\AllergyKeyExtractor;
use OpenEMR\Modules\ClinicalCopilot\Service\FieldKeyExtractor\LabResultKeyExtractor;
use OpenEMR\Modules\ClinicalCopilot\Service\FieldKeyExtractor\MedicationKeyExtractor;
use OpenEMR\Modules\ClinicalCopilot\Service\FieldKeyExtractorFactory;
use PHPUnit\Framework\TestCase;

// Module autoloader (same pattern as AgentClientTest)
spl_autoload_register(static function (string $class): void {
    $prefix = 'OpenEMR\\Modules\\ClinicalCopilot\\';
    if (!str_starts_with($class, $prefix)) {
        return;
    }
    $relative = str_replace('\\', DIRECTORY_SEPARATOR, substr($class, strlen($prefix)));
    $path     = __DIR__ . '/../../../../interface/modules/custom_modules/oe-module-clinical-copilot/src/'
        . $relative . '.php';
    if (file_exists($path)) {
        require_once $path;
    }
});

final class FieldKeyExtractorTest extends TestCase
{
    private const DOC_REF_ID = '77';

    // -----------------------------------------------------------------------
    // LabResultKeyExtractor
    // -----------------------------------------------------------------------

    public function testLabKeyIsDeterministic(): void
    {
        $extractor = new LabResultKeyExtractor();
        $row = ['test_name' => 'Hemoglobin A1c'];

        $key1 = $extractor->naturalKey(self::DOC_REF_ID, $row);
        $key2 = $extractor->naturalKey(self::DOC_REF_ID, $row);

        $this->assertSame($key1, $key2, 'Lab natural key must be deterministic.');
    }

    public function testLabKeyContainsDocRefId(): void
    {
        $extractor = new LabResultKeyExtractor();
        $key = $extractor->naturalKey('doc-888', ['test_name' => 'Cholesterol']);

        $this->assertStringStartsWith('doc-888:', $key, 'Lab key must include doc_ref_id as scope prefix.');
    }

    public function testLabKeyNormalizesCase(): void
    {
        $extractor = new LabResultKeyExtractor();

        $keyLower = $extractor->naturalKey(self::DOC_REF_ID, ['test_name' => 'hemoglobin a1c']);
        $keyUpper = $extractor->naturalKey(self::DOC_REF_ID, ['test_name' => 'HEMOGLOBIN A1C']);
        $keyMixed = $extractor->naturalKey(self::DOC_REF_ID, ['test_name' => 'Hemoglobin A1c']);

        $this->assertSame($keyLower, $keyUpper, 'Lab key must normalize uppercase to lowercase.');
        $this->assertSame($keyLower, $keyMixed, 'Lab key must normalize mixed case to lowercase.');
    }

    public function testLabKeyNormalizesWhitespace(): void
    {
        $extractor = new LabResultKeyExtractor();

        $keyCompact    = $extractor->naturalKey(self::DOC_REF_ID, ['test_name' => 'Glucose Fasting']);
        $keyExtraSpace = $extractor->naturalKey(self::DOC_REF_ID, ['test_name' => 'Glucose  Fasting']);
        $keyTabbed     = $extractor->naturalKey(self::DOC_REF_ID, ['test_name' => "Glucose\tFasting"]);

        $this->assertSame($keyCompact, $keyExtraSpace, 'Lab key must collapse extra spaces.');
        $this->assertSame($keyCompact, $keyTabbed, 'Lab key must treat tab as space.');
    }

    public function testLabKeyDifferentDocRefIdsDifferentKeys(): void
    {
        $extractor = new LabResultKeyExtractor();
        $row = ['test_name' => 'eGFR'];

        $key1 = $extractor->naturalKey('doc-1', $row);
        $key2 = $extractor->naturalKey('doc-2', $row);

        $this->assertNotSame($key1, $key2, 'Lab keys for different doc_ref_ids must differ.');
    }

    public function testLabKeyContainsLabMarker(): void
    {
        $extractor = new LabResultKeyExtractor();
        $key = $extractor->naturalKey(self::DOC_REF_ID, ['test_name' => 'TSH']);

        $this->assertStringContainsString(':lab:', $key, 'Lab key must contain ":lab:" marker.');
    }

    public function testLabKeyEmptyTestName(): void
    {
        $extractor = new LabResultKeyExtractor();
        $key = $extractor->naturalKey(self::DOC_REF_ID, []);

        // Key must not crash and must still contain the doc_ref_id scope.
        $this->assertStringStartsWith(self::DOC_REF_ID . ':', $key);
    }

    // -----------------------------------------------------------------------
    // AllergyKeyExtractor
    // -----------------------------------------------------------------------

    public function testAllergyKeyNormalizesSubstance(): void
    {
        $extractor = new AllergyKeyExtractor();

        $keyLower = $extractor->naturalKey(self::DOC_REF_ID, ['substance' => 'penicillin']);
        $keyUpper = $extractor->naturalKey(self::DOC_REF_ID, ['substance' => 'PENICILLIN']);

        $this->assertSame($keyLower, $keyUpper, 'Allergy key must normalize substance case.');
    }

    public function testAllergyKeyContainsAllergyMarker(): void
    {
        $extractor = new AllergyKeyExtractor();
        $key = $extractor->naturalKey(self::DOC_REF_ID, ['substance' => 'Aspirin']);

        $this->assertStringContainsString(':allergy:', $key, 'Allergy key must contain ":allergy:" marker.');
    }

    public function testAllergyKeyDifferentSubstancesDifferentKeys(): void
    {
        $extractor = new AllergyKeyExtractor();

        $keyPen  = $extractor->naturalKey(self::DOC_REF_ID, ['substance' => 'Penicillin']);
        $keyAsp  = $extractor->naturalKey(self::DOC_REF_ID, ['substance' => 'Aspirin']);

        $this->assertNotSame($keyPen, $keyAsp);
    }

    // -----------------------------------------------------------------------
    // MedicationKeyExtractor
    // -----------------------------------------------------------------------

    public function testMedicationKeyNormalizesName(): void
    {
        $extractor = new MedicationKeyExtractor();

        $keyLower = $extractor->naturalKey(self::DOC_REF_ID, ['name' => 'metformin']);
        $keyUpper = $extractor->naturalKey(self::DOC_REF_ID, ['name' => 'METFORMIN']);

        $this->assertSame($keyLower, $keyUpper, 'Medication key must normalize name case.');
    }

    public function testMedicationKeyContainsMedicationMarker(): void
    {
        $extractor = new MedicationKeyExtractor();
        $key = $extractor->naturalKey(self::DOC_REF_ID, ['name' => 'Metformin']);

        $this->assertStringContainsString(':medication:', $key, 'Medication key must contain ":medication:" marker.');
    }

    // -----------------------------------------------------------------------
    // FieldKeyExtractorFactory
    // -----------------------------------------------------------------------

    /**
     * @return array<string, array{string, class-string}>
     *
     * @codeCoverageIgnore Data providers run before coverage instrumentation starts.
     */
    public static function factoryCompositeKeyProvider(): array
    {
        return [
            'lab_pdf:result'         => ['lab_pdf:result',         LabResultKeyExtractor::class],
            'intake_form:allergy'    => ['intake_form:allergy',    AllergyKeyExtractor::class],
            'intake_form:medication' => ['intake_form:medication', MedicationKeyExtractor::class],
        ];
    }

    /**
     * @dataProvider factoryCompositeKeyProvider
     */
    public function testFactoryReturnsCorrectImplementation(string $compositeKey, string $expectedClass): void
    {
        $factory   = new FieldKeyExtractorFactory();
        $extractor = $factory->get($compositeKey);

        $this->assertInstanceOf($expectedClass, $extractor);
    }

    public function testFactoryThrowsOnUnknownKey(): void
    {
        $factory = new FieldKeyExtractorFactory();

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessageMatches('/unknown_key/');

        $factory->get('unknown_key');
    }

    // -----------------------------------------------------------------------
    // Risk 1: "nk:" prefix collision contract
    //
    // Docling emits block_ids in "block_N" format (see __init__.py line 222).
    // A real Docling block_id CANNOT start with "nk:" under that convention.
    // This test documents the contract by asserting a Docling-format block_id
    // does not match the "nk:" prefix used by insertNaturalKeyIndex().
    //
    // If this test fails it means Docling changed its naming convention and
    // the disambiguation logic in RoundtripService::findClinicalRowByNaturalKey
    // must be updated to use a separate column (not source_block_id).
    // -----------------------------------------------------------------------

    /**
     * Docling block ids use "block_N" format and therefore never start with "nk:".
     *
     * @return array<string, array{string}>
     *
     * @codeCoverageIgnore Data providers run before coverage instrumentation starts.
     */
    public static function doclingBlockIdProvider(): array
    {
        return [
            'block_0'   => ['block_0'],
            'block_1'   => ['block_1'],
            'block_99'  => ['block_99'],
            'block_999' => ['block_999'],
        ];
    }

    /**
     * @dataProvider doclingBlockIdProvider
     */
    public function testDoclingBlockIdNeverStartsWithNkPrefix(string $blockId): void
    {
        $this->assertStringStartsNotWith(
            'nk:',
            $blockId,
            "Docling block_id '{$blockId}' must not start with 'nk:' — that prefix is "
            . 'reserved for natural-key carrier rows in co_pilot_fhir_links.source_block_id. '
            . 'If Docling changed its naming convention, update RoundtripService disambig logic.',
        );
    }

    /**
     * A natural key produced by LabResultKeyExtractor, when stored with "nk:" prefix,
     * is always distinguishable from a real Docling block_id stored without prefix.
     */
    public function testNkPrefixedNaturalKeyDistinguishableFromDoclingBlockId(): void
    {
        $extractor  = new LabResultKeyExtractor();
        $naturalKey = $extractor->naturalKey('doc-77', ['test_name' => 'Glucose']);
        $storedKey  = 'nk:' . $naturalKey;

        // Real Docling block_id format (from __init__.py line 222: "block_{block_index}")
        $doclingBlockId = 'block_0';

        $this->assertStringStartsWith('nk:', $storedKey);
        $this->assertStringStartsNotWith('nk:', $doclingBlockId);
        $this->assertNotSame($storedKey, $doclingBlockId);
    }
}
